# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf218c62ddccd9bf72047beb3019bd00855192749249bf18a24410f8cd60645f76ef39dd57e15c314372720db0c8cecb707f2416d8c0f078ae30a472f3a5130c

test:
  secret_key_base: cbb29e4d84b298ca267fc8c9ba37f27f91260623b46500af58473ce3f3982c7a9aa52358c5546bab0e395d6277129ac77bc22cc55f8cd10d4ced9baed4a8889e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
